/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "secondary": "#d7ffc5",
                "outline": "#849495",
                "tertiary": "#fff4f9",
                "surface-container-low": "#191c22",
                "error": "#ffb4ab",
                "primary": "#e1fdff",
                "secondary-fixed": "#79ff5b",
                "surface-variant": "#32353c",
                "tertiary-fixed": "#ffd7f5",
                "on-secondary-fixed": "#022100",
                "on-primary-fixed-variant": "#004f54",
                "on-secondary-fixed-variant": "#095300",
                "surface-container-highest": "#32353c",
                "on-error": "#690005",
                "tertiary-container": "#ffcbf4",
                "on-secondary-container": "#0f6d00",
                "on-error-container": "#ffdad6",
                "outline-variant": "#3a494b",
                "background": "#10131a",
                "secondary-fixed-dim": "#2ae500",
                "primary-fixed-dim": "#00dbe7",
                "primary-fixed": "#74f5ff",
                "on-surface-variant": "#b9cacb",
                "on-tertiary-fixed": "#380038",
                "surface": "#10131a",
                "surface-tint": "#00dbe7",
                "surface-bright": "#363940",
                "on-tertiary-fixed-variant": "#810081",
                "surface-container": "#1d2026",
                "tertiary-fixed-dim": "#ffabf3",
                "on-primary-container": "#006a71",
                "secondary-container": "#2ff801",
                "inverse-surface": "#e1e2eb",
                "on-tertiary-container": "#ab00aa",
                "on-background": "#e1e2eb",
                "on-secondary": "#053900",
                "surface-dim": "#10131a",
                "inverse-primary": "#00696f",
                "on-surface": "#e1e2eb",
                "inverse-on-surface": "#2e3037",
                "on-primary": "#00363a",
                "primary-container": "#00f2ff",
                "surface-container-lowest": "#0b0e14",
                "on-primary-fixed": "#002022",
                "error-container": "#93000a",
                "on-tertiary": "#5b005b",
                "surface-container-high": "#272a31"
            },
            fontFamily: {
                "headline": ["Space Grotesk", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"],
                "mono": ["Roboto Mono", "monospace"]
            },
            borderRadius: {
              "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"
            },
        },
    },
    plugins: [],
}
